/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts;

import hibernate.User;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.web.struts.ActionSupport;
import spring.UserService;
import struts.UserLoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-05-2017
 * 
 * XDoclet definition:
 * @struts.action path="/userLogin" name="userLoginForm" input="/form/userLogin.jsp" scope="request" validate="true"
 */
public class UserLoginAction extends ActionSupport {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserLoginForm userLoginForm = (UserLoginForm) form;// TODO Auto-generated method stub
		
		ActionForward forward = mapping.getInputForward();
		
		String username = userLoginForm.getUsername();
		String password = userLoginForm.getPassword();
		
		UserService service = (UserService)getWebApplicationContext().getBean("UserService");
		
		User userFormDB = service.getUserByUsername(username);
		
		if (userFormDB != null){
			if (password.equals(userFormDB.getPassword())){
				forward = mapping.findForward("success");
			}else{
				forward = mapping.findForward("failure");
			}
			
		}
		return forward;
//		request.setAttribute("username", userLoginForm.getUsername());
//		
//		if(userLoginForm.getUsername().equals("muyonghui")&&userLoginForm.getPassword().equals("123")){
//			return mapping.findForward("success");
//		}else{
//			return mapping.findForward("failure");
//		}
		
	}
}